__include__: [
  '../ecdet/ecdet_l.yml',
  '../dataset/bee_e_13.yml',
]

output_dir: /data/bee26/beeposetrack_e_20260827/work_dirs/e0_l_640
eval_spatial_size: [640, 640]
epochs: 50
warmup_iter: 100
checkpoint_freq: 10
print_freq: 20
grad_accum_steps: 16

train_dataloader:
  total_batch_size: 1
  dataset:
    transforms:
      mosaic_epoch: 24
      mosaic_prob: 0.5
      stop_epoch: 48
  collate_fn:
    mixup_prob: 0.5
    mixup_epoch: 24

val_dataloader:
  total_batch_size: 1

PostProcessor:
  num_top_queries: 300
