__include__: [
  'e1_s_p2_q768_960.yml',
]

output_dir: /data/bee26/beeposetrack_e_20260827/work_dirs/e1_s_p2_q300_smoke
eval_spatial_size: [128, 128]
epochs: 1
warmup_iter: 1
checkpoint_freq: 1
print_freq: 1
sync_bn: False
use_ema: False
grad_accum_steps: 1

ECTransformer:
  num_queries: 300

train_dataloader:
  total_batch_size: 2
  num_workers: 0
  dataset:
    ann_file: /data/bee26/beeposetrack_e_20260827/data/annotations/train_13_smoke.json
    transforms:
      stop_epoch: 1

val_dataloader:
  total_batch_size: 2
  num_workers: 0
  dataset:
    ann_file: /data/bee26/beeposetrack_e_20260827/data/annotations/val_13_smoke.json

PostProcessor:
  num_top_queries: 300

evaluator:
  max_dets: [1, 10, 300]
