__include__: [
  'e2_s_joint_direct_1280.yml',
]

output_dir: /data/bee26/beeposetrack_e_20260827/work_dirs/e3_s_joint_density_1280

ECDet:
  enable_density: True
  density_in_channels: 192
  density_hidden_channels: 96

ECCriterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5,
                loss_keypoint: 10, loss_direction: 1, loss_visibility: 0.2,
                loss_density_map: 1, loss_density_count: 1}
  losses: ['mal', 'boxes', 'local', 'pose', 'density']

